CONTIKI_PROJECT = example-runicast
CONTIKI = ../../contiki
all: $(CONTIKI_PROJECT)

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
DEFINES += PROJECT_CONF_H=\"project-conf.h\"
PROJECT_SOURCEFILES += sample.csv 